# Generated by Django 5.1.7 on 2025-04-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inputdata_resume_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='education',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='skills_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
